### ISSUE TITLE
Modificar vista listado.

### ISSUE THREAD

**Issue by AnaMariaRomero** [lasolUndav/pes#41]
Se superpone el contenido cuando las líneas del mat-list-item son variadas.

**Comment by lasolUndav** [comment]
Una recomendacion:

- Los tags de rubro tienen el mismo color que los botones de acción secundario (class accent: ver, editar, eliminar). Quizas podrian ser grises como los del formulario, tal vez con ponerlos debajo del nombre se solucione el tema de la superposicion?
